/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as StudyResourceIdRouteImport } from './routes/study.$resourceId'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyResourceIdRoute = StudyResourceIdRouteImport.update({
  id: '/study/$resourceId',
  path: '/study/$resourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/graph': typeof GraphRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/organizer': typeof OrganizerRoute
  '/progress': typeof ProgressRoute
  '/recap': typeof RecapRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/workspaces': typeof WorkspacesRoute
  '/study/$resourceId': typeof StudyResourceIdRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/graph': typeof GraphRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/organizer': typeof OrganizerRoute
  '/progress': typeof ProgressRoute
  '/recap': typeof RecapRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/workspaces': typeof WorkspacesRoute
  '/study/$resourceId': typeof StudyResourceIdRoute
  '/study': typeof StudyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/graph': typeof GraphRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/organizer': typeof OrganizerRoute
  '/progress': typeof ProgressRoute
  '/recap': typeof RecapRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/workspaces': typeof WorkspacesRoute
  '/study/$resourceId': typeof StudyResourceIdRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flashcards'
    | '/graph'
    | '/library'
    | '/notes'
    | '/onboarding'
    | '/organizer'
    | '/progress'
    | '/recap'
    | '/settings'
    | '/trash'
    | '/workspaces'
    | '/study/$resourceId'
    | '/study/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flashcards'
    | '/graph'
    | '/library'
    | '/notes'
    | '/onboarding'
    | '/organizer'
    | '/progress'
    | '/recap'
    | '/settings'
    | '/trash'
    | '/workspaces'
    | '/study/$resourceId'
    | '/study'
  id:
    | '__root__'
    | '/'
    | '/flashcards'
    | '/graph'
    | '/library'
    | '/notes'
    | '/onboarding'
    | '/organizer'
    | '/progress'
    | '/recap'
    | '/settings'
    | '/trash'
    | '/workspaces'
    | '/study/$resourceId'
    | '/study/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlashcardsRoute: typeof FlashcardsRoute
  GraphRoute: typeof GraphRoute
  LibraryRoute: typeof LibraryRoute
  NotesRoute: typeof NotesRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganizerRoute: typeof OrganizerRoute
  ProgressRoute: typeof ProgressRoute
  RecapRoute: typeof RecapRoute
  SettingsRoute: typeof SettingsRoute
  TrashRoute: typeof TrashRoute
  WorkspacesRoute: typeof WorkspacesRoute
  StudyResourceIdRoute: typeof StudyResourceIdRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$resourceId': {
      id: '/study/$resourceId'
      path: '/study/$resourceId'
      fullPath: '/study/$resourceId'
      preLoaderRoute: typeof StudyResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlashcardsRoute: FlashcardsRoute,
  GraphRoute: GraphRoute,
  LibraryRoute: LibraryRoute,
  NotesRoute: NotesRoute,
  OnboardingRoute: OnboardingRoute,
  OrganizerRoute: OrganizerRoute,
  ProgressRoute: ProgressRoute,
  RecapRoute: RecapRoute,
  SettingsRoute: SettingsRoute,
  TrashRoute: TrashRoute,
  WorkspacesRoute: WorkspacesRoute,
  StudyResourceIdRoute: StudyResourceIdRoute,
  StudyIndexRoute: StudyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
